---
title: "Projects"
toc: true
toc-title: Contents
toc-location: left
---

Here are some of my past and current projects:

# Active Projects

## Invasive Species RShiny Dashboard

#### Purpose:
This project is complete. The dashboard is currently hosted on [shinyapps.io](https://0uexv8-johann-wagner.shinyapps.io/invasive_species_dashboard/). The dashboard is still in the early stages of development and there are still many improvements to be made. The next step is to incorporate the dashboard into this website and share this work with the Atlas of Living Australia.

#### Project Scope:

This project was the final assignment for the [Data Science for Biologists (DS4B)](https://programsandcourses.anu.edu.au/2023/course/biol3207) university course.

The project had the following brief: Your task is to:

-   choose a dataset or combination of datasets
-   develop some questions/aims related to that dataset, including appropriate background research
-   use R t |> o address those questions/aims
-   write your findings into a report of up to 2000 words and 10 figures
-   summarise your findings in a poster which you will present in the week 12 workshop

Ideally, you should choose a combination of dataset and questions/aims that are interesting to you, because the more interesting you find it, the better your work will be!

#### Links:

-   [RShiny Dashboard](https://0uexv8-johann-wagner.shinyapps.io/invasive_species_dashboard/)

-   [Poster](https://github.com/johann-wagner/DS4B-final-project/blob/main/u6958957_poster.pdf)

-   [GitHub Repository](https://github.com/johann-wagner/DS4B-final-project)

## Spotify Exploratory Data Analysis

#### Purpose:
Explore Johann's personal Spotify data and discover patterns in his listening habits.

#### Project Status:
-   Currently working on looking at the streaming history data.
-   Next step is to look at the playlist data and await the entire streaming history data to be available (late Jan 2024).
-   The final step is to create an RShiny dashboard to visualise the data and create some basic descriptive statistics.
-   Ideally, this RShiny will allow individuals to upload their own personal Spotify data and explore their own listening habits.
-   Additionally, I would like to recreate my own version of the Spotify Wrapped.
-   Need to explore the Spotify API and see how I can integrate it into the RShiny dashboard.
-   Look into other people's Spotify and R projects to see what I can learn from them.

#### Links:
-   [GitHub Repository](https://github.com/johann-wagner/spotify-analysis).
-   [Spotify API](https://developer.spotify.com/documentation/web-api/).

## D20 Simulation

#### Purpose:

Calculating the probability mass function of a d20 twenty times and adding a rule of rolling another 6 times if a 20 is rolled.

#### Project Status:
-   Create an RShiny Dashboard
-   Rewrite the code to incorporate `rbinom()`, instead of using `runif()`.

#### Links:

-   [GitHub Repository](https://github.com/johann-wagner/d20-simulation)

## Leadership Compass

#### Purpose:

Create an R script that creates a visualisation of the results from the leadership compass survey.

#### Project Status:

This project is currently in progress. There are still major improvements to be made to the visualisation and the data workflow. An excel file containing the survey results is currently being used as the data source. The next step is to create a Google Form to collect the survey results and then use the Google Form API to pull the data into the R script. Potentially, this can further be all incoroprated into an RShiny App.

#### Links:

-   [GitHub Repository](https://github.com/johann-wagner/leadership_compass)
