---
title: "Bikepacking - Attack of the Buns"
description: "A hot 4-day adventure through Morton National Park"
author: "Johann Wagner"
date: "2025-03-15"
categories:
  - "Bikepacking"
  - "Adventure"
---

Attack of the Buns.... Or perhaps rather Attack of the Braids, because instead of a Bungendore start we began the adventure from Braidwood. [Add more table of contents vibes]

Day 0: Car Logistics
The trip began after work on a Wednesday afternoon. The idea was Robin and I would drive separately from Canberra to Moss Vale. We would then "scissors, paper, rock" to determine who's car would be left in Moss Vale. Then we would grab Subway and head back home to Canberra. With our bikes and gear now all packed in the car, it was time for an early nights sleep.

The plan from here would be to drive to Braidwood, then cycle across 4 days back to the car in Moss Vale and then collect the other car in Braidwood back to Canberra. The alternatives would have been getting someone to pick us up from Moss Vale or catching the train back to Canberra. Having overestimated our bikepacking speed in the past, the convenience of having our own transportation post-bike leg was very worth the Wednesday afternoon effort.

Day 1: A bike pump, Nerriga Pub, and some night time reflections [Braidwood to Piercys Clearing]

Today was the first day where (almost) everything went to plan - a rariety in my bikepacking career so far.

Awake and ready the day after, we would make our way straight to Braidwood for some breakfast pies from the local bakery. The bikes and bags are now fully setup, we've taken our first of many 10 second self-timer photos, excited to go, Robin wants to quickly pump up his tires before we hit the gravel. To our surprise, we realise shortly after that I had forgotten to bring the valve adaptor. 

[Insert side read on valve types] 

In a worried manner, we push our bikes through town asking shopkeepers if they sell bike pumps. The local outdoor shop ... negative
The petrol station ... negative
The local IGA ... negative 

Braidwood Mitre 10 ... a full-sized bike pump, which we strap onto my front handle bars with some spare straps I brought (a reminder to always bring some spare straps!).

And off we go having already problem solved, we jump onto Little River Road leading onto Charleys Forest Road off to Nerriga. The gravel was smooth and slightly undulating. Complimented by a cool misty morning, we were flying past grazing cattle, calm creek crossings, and a peaceful snake enjoying the warm road! 

With the sun starting to break through the clouds, arriving at Nerriga was a lifesaver from the incoming onslaught of the heat. Excited to down a celebratory pint of Carlton Draught and a pub feed, we were greeted by two confused looking locals joking they would have preferred taking their motorbikes instead of bicycles. I followed with a slight nod and a chuckle, as I gazed over to see another bikepacker enjoying the shade. Not able to wait any longer, I rush inside to see a bustling pub full of elderly people enjoying their meals. I order the pub burger and my pint and head outside curious to hear where the other bikepacker had come from. 

Lachie had the full bike setup, a bunch of bike bags, mountain bike cleets, thick tires, and even some tri bars. I knew I was just about to meet an expert in the field. Offering a seat to his table, we had lunch with him finding out he had just come from Gerringong via the same route we had planned - only to realise his final destination was not Braidwood, but in fact Tasmania....

After exchanging stories and advice, Robin and I left for our afternoon session. Back on gravel, we came across Endrick River, a lovely swimming spot by a small shady forde. We continued through Morton National Park overlooking some marvellous cliff faces following along The Red Ground Track. After a small mishaps in navigation, we arrived at Piercy's Clearing just off a smaller estuary of Endrick River. A quick rinse off followed by some Backcountry freeze-dried Satay Chicken and some much needed stretching, we were ready to for sleep.

Laying on my mat resting my head against my rolled up sleeping bag. The current sleeping arrangements are a cosy 1-person tent with a luxuriously large Sea to Summit sleeping mat. Planning on using my sleeping bag liner and keeping the bag packed up given its a warmish night. Reflecting through photos and videos of the day feeling my joints relax and recover after a warm days ride. Listening to the rustling shoulders against the mat searching for the optimal position, I finally get comfortable and wrap myself in the liner. Immediately, I feel the merino radiating and slowly close my eyes to the whispers of crickets and creaking nocturnal animal life in the distance. Hopefully I still have all my food in the morning! Good night.

Day 2: Rocky flats & sandy downhills, sweating profusely, and motel magic

It always seems like I struggle having breakfast. Consistent food intake is so so important when it comes to endurance events. So when I know there's a long, sunny day ahead, I'll aim to eat as much as I can for breakfast and essentially every other meal of the day. Today's menu: 
- Breakfast (at Piercy's Clearing): Porridge, Nutella, Salami, Hazelnut Coffee 
- Lunch (at Yalwal): Backcountry Moroccan Lamb
- Dinner (in Nowra): Pizza, Bundaberg Guava
- Dessert (at the motel): Maxibon, chocie milk
- Snacks (constantly): Peanut M&Ms, Salted nuts, Soya Crisps, Gu gels, Powerade

Today's first few kilometres are met with large rocky sections making a very slow start. I'm surprised we didn't get any flat tubes as it was very technical riding on our thin gravel tires. We finally made it out of that "hell-ish" (footnote: we met another bikepacker racing in the Sydney to Summit race, who greeted us with "welcome to hell", as he was flowing down the mountain. I think he was in a lot of pain, the type 3 dark pain) rocky section to arrive on top of the clouds overlooking the valley we'd just been sleeping in. It's and awesome feeling looking out into the distance on the cliff tops, feeling a slight breeze on your face surrounded by eucalypts and a fire trail dancing along the ridgeline. That was one of the highlights of that trip gazing out into the distance.

Back into action, we get back onto tarmac for a sweet 75km/h+ speedy descent down Braidwood Road shortly after jumping back onto the gravel following Yarramunmun Firetrail. Now we had switched from rocky technicals to the sandy downhills. Whilst the downhill was appreciated, the heat reflecting off the white-beige sand radiated for what felt for a few monotonous hours. Thankfully, after an incredibly steep descent, we finally made it into Yalwal, a camping green space next to one of Shoalhavens several dams. Seeking out shelter, we spent over 2 hours eating, attempting to rehydrate and recover in preparation for a big climb out of the basin. After a backcountry, way too many M&Ms, several chugs of my warm Powerade, we were as ready as could be for the climb.

Powering out is a mental game, a tug of war between pushing on through the lactic acid or taking a break in the shade. The latter is promising, but the ego says otherwise. At some point, the body gets used to the pain, some even each the nirvana type 2 fun state of mind of enjoying the pain. The mind slowly gets filled with echoes of doubt, but also reminders of triumph and motivation. The grit comes out and you power through sometimes even zoning out or perhaps it's actually zoning in; into a state of mind where the only objective is "push". Enough meta type 2 fun talk, back to the day. 

Making it up to the top, I see a sun-protected area, whip out my luxury-item cushioned mats, sit back and enjoy the last above lukewarm temperature red Powerade. I'm running low on snacks, I'm excited for Nowra. Robin and I enjoy some more shade listening to our nostalgic 2010s (arguably emo/edm phase) music, hop on the saddle heading east to Nowra. 

Getting back into a busy town, especially over the summer weekend, was a little bit of a shock. So much stopping and starting. We get into Nowra CBD and I propose to Robbie, that I quickly run into Coles to grab a 2L Oak chocie milk... Best decision. I had about a whole liter within a few minutes.

Getting to the motel made me really appreciate all the common household services, like a cold shower, a microwave, a bed, an aircon (omg the aircon was immediately turned on upon entering!), a chair and table, fresh drinkable cold water. What luxuries. As someone who's only recently gotten into camping, this must be a common experience to those more experienced, but alas a nice personal appreciation.

We finished off the day with some local woodfired pizzas and a snack restock at Coles. Returning to the aircon-chilled room and covering up under blankets over a cushiony bed was a lovely change (can't believe I appreciated this so much given it was only one night of camping eeeep).
