project:
  type: website
  output-dir: docs

website:
  title: "Johann Wagner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/johannwagner/
      - icon: github
        text: GitHub
        href: https://github.com/johann-wagner
      - icon: envelope
        text: Email
        href: "mailto:johann.wagner@gmail.com"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



