# This file controls the settings for my Quarto website.

# Website Settings
website:
  title: "Johann Wagner"
  description: "Core Values: Balance, Love, Community"

  navbar:
    pinned: true

    # Sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd

      - text: "Blog"
        href: blog/index.qmd

      - text: "CV"
        href: cv/index.qmd


    # Social Media Links
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/johannwagner/
      - icon: github
        href: https://github.com/johann-wagner
      - icon: envelope
        href: "mailto:johann.wagner@gmail.com"

  search:
    location: navbar
    type: textbox
  page-footer:
    left: |
      <span class="faux-block">&#169; 2023 Johann Wagner CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/johann-wagner/johann-wagner">View source code on my GitHub</a></span>

project:
  type: website
  output-dir: docs
  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

# Theme Settings
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



